### PR TITLE
2020-04-01 Agenda

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@armstro @1000TurquoisePogs @Joe-Winchester @MarkAckert @solsu01 Please review and approve if the agenda is in there correctly - thanks!

**Comment by 1000TurquoisePogs** [comment]
Is the deletion of some videos of prior meetings intentional?

**Comment by jmertic** [comment]
I don't think I deleted any of them - they were just never in the repo. I can hunt through Zoom and add them in if y'all want.

**Comment by armstro** [comment]
As acting ZLC Chair I have not done anything with the Zoom recordings over the past several months - they should be in Zoom assuming they are not auto deleted after some period of time

**Comment by 1000TurquoisePogs** [comment]
Oh! I was wrong. red text on the git diff of a binary usually means deleted to me. It meant the LFS toggle saved space. All good.

**Review by 1000TurquoisePogs — APPROVED** [review]

**Pull request merged**
