### PR TITLE
First pass at bringing in Zowe Charter items into these docs.

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by Tbr00ksy** [comment]
In the "process" md, you propose: "Elections are held during the months of June or July with the following schedule:"

Would it make sense to make this align with a conference where we know the majority of ZLC members will be. For example, if we align with SHARE perhaps we say elections are held during the months of August or September.

**Comment by jmertic** [comment]
So we don't need to do elections in person - most communities do it electronically. Probably best to not do elections right before/around a big event like that.

**Comment by Tbr00ksy** [comment]
@jmertic In reviewing the voting, in the process/structure md., it does not specify who is able to vote for the ZLC (I assume only committers are allowed to vote for ZLC), or how many votes is a committer is allowed to cast. Are there any guidelines from other projects that have a leadership committee you are aware of?

**Comment by jmertic** [comment]
Hey @Tbr00ksy - look in the "Composition" section. It spells out that any committer to a Zowe sub-project can vote or be nominated to serve on the ZLC.

Regarding number of votes to cast, typically a single person would elect up to the number of individuals to serve ( so presuming the size of the ZLC stays at 6, each committer would select 6 persons ). Does that answer your question?

**Comment by Tbr00ksy** [comment]
@jmertic does the OMP have a tool other than our groups.io email that we could use for the election/voting? 

Also if each voter (committer) is able to cast 6 votes, does that mean that the top 6 highest receiving nominated committers make up the ZLC? For example, if we have 9 nominated committers looking to represent the community, the top 6 with the highest number of votes make up the community. Can a committer with 6 votes cast all 6 votes for a single individual? 

Also, once the ZLC is elected is there then another vote among the ZLC to determine the project maintainer?

**Comment by jmertic** [comment]
We use the CIVS for voting ( https://civs.cs.cornell.edu/ ) - that is also referenced in the docs :-). CIVS basically takes care of the concerns you have on tie-breaking and double voting as it does proportional voting. 

And yes, typically the chairperson is selected by the leadership committee, not by broad vote. This was also done to select the initial ZLC chair.

**Comment by 1000TurquoisePogs** [comment]
I see a few issues in this branch, some are just because I don't think we finished deciding

- The active projects lists "Zowe Web Desktop", but this isn't the term used in documentation, which is "Zowe Application Framework".
- The ZLC is listed as being 6 members, with 3 being added every 2 years, but we need to decide
- It attempts to make contributors bound to https://events.linuxfoundation.org/code-of-conduct/ but this seems irrelevant, given that it deals with event business. If a contributor is never going to attend an event, why bother? This seems like something that an event attendee would agree to upon purchasing an event ticket, not beforehand.
- The release cycle document mentions that we release monthly, but I believe there was a recent suggestion to slow down slightly to give more time for post-code-freeze validation. Should we rephrase this?
- The UI guidelines use examples that reference websites external to Zowe code. On mainframe software, I believe it's generally frowned upon to have software rely upon internet resources due to network security restrictions & firewalls. Does anyone have alternative UI guideline suggestions to amend with?

**Comment by jmertic** [comment]
Good comments @1000TurquoisePogs - let me touch on these inline...

> I see a few issues in this branch, some are just because I don't think we finished deciding
> 
> * The active projects lists "Zowe Web Desktop", but this isn't the term used in documentation, which is "Zowe Application Framework".

Picking the name isn't meant to be authoritative from me, but more to provoke the discussion. Agreed that there should be consistency here - would be great for that sub-project to come up with the correct terminology.

> * The ZLC is listed as being 6 members, with 3 being added every 2 years, but we need to decide

Yep - again meant to provoke discussion. 

> * It attempts to make contributors bound to https://events.linuxfoundation.org/code-of-conduct/ but this seems irrelevant, given that it deals with event business. If a contributor is never going to attend an event, why bother? This seems like something that an event attendee would agree to upon purchasing an event ticket, not beforehand.

I do agree with you there. I think aligning with the LF Projects LLC CoC likely is more accurate here. Take a look and let me know your thoughts -> https://lfprojects.org/policies/code-of-conduct/

> * The release cycle document mentions that we release monthly, but I believe there was a recent suggestion to slow down slightly to give more time for post-code-freeze validation. Should we rephrase this?

Many projects keep this vague in the governance docs and instead reference a release schedule doc which gives the team some wiggle room.  Not sure if that's a better solution here or not.

> * The UI guidelines use examples that reference websites external to Zowe code. On mainframe software, I believe it's generally frowned upon to have software rely upon internet resources due to network security restrictions & firewalls. Does anyone have alternative UI guideline suggestions to amend with?

I pulled this from zowe.org - not sure if it's accurate or not. Might make sense to revisit.

**Comment by jmertic** [comment]
Connected with the issue open on this.

Where do we stand here? It sounds like the open issues are:

- Definition of 'active committer'?
- Confirmation of active projects and their names
- CoC selection

Anything else I'm missing?

**Review by hogstrom — APPROVED** [review]
Merging all commits in this branch to bring the ZLC docs up to date.

**Pull request merged**
